"""2024-04-25_remove_dynamic_user_data_from_table

Revision ID: ac80dd492c40
Revises: ba6b397ec577
Create Date: 2024-04-25 12:44:10.162873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac80dd492c40'
down_revision = 'ba6b397ec577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_image_id')
        batch_op.drop_column('user_name')
        batch_op.drop_column('user_followers')
        batch_op.drop_column('user_country')
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_country', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_followers', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_image_id', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
